### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv.runner.log_buffer'

### ISSUE THREAD

**Issue by muhabdulhaq** [hqucv/dmtrack#2]
I got some problem when installing, can you help me? Thanks

```
>> python tools/train_dmtrack.py
Traceback (most recent call last):
  File "tools/train_dmtrack.py", line 6, in <module>
    import _init_paths
  File ">>/dmtrack/_init_paths.py", line 6, in <module>
    from modules import *
  File ">>/dmtrack/modules/__init__.py", line 1, in <module>
    from .cond_conv import *
  File ">>/dmtrack/modules/cond_conv.py", line 3, in <module>
    from mmcv.cnn import normal_init
  File ">>/dmtrack/_submodules/mmcv/mmcv/cnn/__init__.py", line 2, in <module>
    from .alexnet import AlexNet
  File ">>/dmtrack/_submodules/mmcv/mmcv/cnn/alexnet.py", line 6, in <module>
    from ..runner import load_checkpoint
  File ">>/dmtrack/_submodules/mmcv/mmcv/runner/__init__.py", line 9, in <module>
    from .log_buffer import LogBuffer
ModuleNotFoundError: No module named 'mmcv.runner.log_buffer'
```

**Comment by JackjackFan** [comment]
你解决这个问题了吗？
